### ISSUE TITLE
Redundancy of "isInsurance" attribute

### ISSUE THREAD

**Issue by ThyMYthOS** [gematik/api-vzd#81]
In https://github.com/gematik/api-vzd/blob/09ef02fea0e8ada5e6ec7e7bb7f6ab3c56cdd62b/src/openapi/I_VZD_TIM_Provider_Services.yaml#L475 there are the fields `telematikID` and `isInsurance`. As far as I know the prefix of the TelematikID already indicates the type of organisation.

So why is there a separate field?

**Comment by gem-uhe** [comment]
Do you have in all scenarios a telematikID? 
TI-Messenger users may be also workers in medical organizations without cards (HBA/SMC-B) and no entry in the VZD.
In TIM 2.0 insured person can be TIM users. For these insured persons the isInsurance flag was created. It marks the domains of insured persons.

**Comment by ThyMYthOS** [comment]
I'm talking specifically about this object:
``` yaml
    Domain:
      type: object
      required:
          - domain
          - telematikID
          - isInsurance
      properties:
        domain:
          description: The TI-Messenger domain
          type: string
        telematikID:
          description: The telematikID of the organization that uses the TI-Messenger domain
          type: string
        isInsurance:
          description: |
               Indicates if it is a domain of an health insurance for insured persons
          type: boolean
          default: false          
          example: false
```

The `telematikID` is not optional, so I guess every organization has one. The `isInsurance` field is not for insured persons but for insurance companies. So I still think it's redundant.
